from typing import List, Any
import json
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException
from auth.deps import get_current_user
from database.database import get_db
from prisma.models import User, UserProgress, Curriculum
from schemas.learning_path import (
    UserProgressCreate,
    UserProgressInDB,
    ContentRecommendation,
    ProficiencyPrediction,
    PersonalizedLessonRequest,
    PersonalizedLessonResponse
)
from services.recommendation import get_content_recommendations, predict_proficiency
from services.llm import generate_personalized_lesson

router = APIRouter()

@router.get("/recommendations", response_model=List[ContentRecommendation])
async def get_recommendations(current_user: User = Depends(get_current_user)):
    """Get content recommendations for the user."""
    recommendations = await get_content_recommendations(current_user.id)
    return recommendations

@router.get("/custom_lessons")
async def get_custom_lessons(current_user: User = Depends(get_current_user)):
    """Get custom lessons generated by the user."""
    db = get_db()
    lessons = await db.curriculum.find_many(where={"user_id": current_user.id, "is_custom": True})
    
    # Also fetch the progress for these lessons to show attempt count and score
    progresses = await db.userprogress.find_many(
        where={
            "user_id": current_user.id,
            "curriculum_id": {"in": [l.id for l in lessons]}
        }
    )
    progress_map = {p.curriculum_id: p for p in progresses}
    
    result = []
    for lesson in lessons:
        prog = progress_map.get(lesson.id)
        result.append({
            "id": lesson.id,
            "title": lesson.title,
            "level": lesson.level,
            "duration": lesson.duration,
            "attempts": prog.attempts if prog else 0,
            "highest_score": prog.score if prog else None,
            "history": json.loads(prog.history) if prog and isinstance(prog.history, str) else (prog.history if prog else [])
        })
    return result

@router.get("/proficiency", response_model=ProficiencyPrediction)
async def get_user_proficiency(current_user: User = Depends(get_current_user)):
    """Predict the user's current proficiency level."""
    prediction = await predict_proficiency(current_user.id)
    return prediction

@router.post("/progress")
async def update_progress(progress_in: UserProgressCreate, current_user: User = Depends(get_current_user)):
    """Record that the user has started or completed a curriculum item."""
    db = get_db()
    
    curriculum = await db.curriculum.find_unique(where={"id": progress_in.curriculum_id})
    if not curriculum:
        raise HTTPException(status_code=404, detail="Curriculum not found")
        
    existing = await db.userprogress.find_first(
        where={
            "user_id": current_user.id,
            "curriculum_id": progress_in.curriculum_id
        }
    )
    
    new_history_entry = {
        "attempt": existing.attempts + 1 if existing else 1,
        "score": progress_in.score,
        "date": datetime.now().isoformat()
    }
    
    if existing:
        current_history = json.loads(existing.history) if isinstance(existing.history, str) else (existing.history or [])
        current_history.append(new_history_entry)
        
        # Keep the highest score
        highest_score = existing.score
        if progress_in.score is not None:
            if highest_score is None or progress_in.score > highest_score:
                highest_score = progress_in.score

        updated = await db.userprogress.update(
            where={"id": existing.id},
            data={
                "status": progress_in.status,
                "score": highest_score,
                "attempts": existing.attempts + 1,
                "history": json.dumps(current_history),
                "completed_at": datetime.now()
            }
        )
        return updated
    else:
        created = await db.userprogress.create(
            data={
                "user_id": current_user.id,
                "curriculum_id": progress_in.curriculum_id,
                "status": progress_in.status,
                "score": progress_in.score,
                "attempts": 1,
                "history": json.dumps([new_history_entry]),
                "completed_at": datetime.now()
            }
        )
        return created

@router.post("/generate_lesson")
async def generate_lesson(request: PersonalizedLessonRequest, current_user: User = Depends(get_current_user)):
    """Generate a personalized learning workflow (lesson + quiz) using AI."""
    level = request.proficiency_level
    if not level:
        prediction = await predict_proficiency(current_user.id)
        level = prediction.get("predicted_level", "Beginner")
        
    try:
        data = await generate_personalized_lesson(request.topic, level, current_user.id)
        return data.get("lesson_data")
    except Exception as e:
        error_str = str(e)
        if "429" in error_str or "quota" in error_str.lower():
            raise HTTPException(status_code=429, detail="AI rate limit exceeded. Please wait a minute and try again!")
        raise HTTPException(status_code=500, detail=f"Failed to generate lesson: {e}")

@router.get("/curriculum/{id}")
async def get_curriculum(id: int, current_user: User = Depends(get_current_user)):
    """Fetch a specific lesson and its quizzes."""
    db = get_db()
    lesson = await db.curriculum.find_unique(
        where={"id": id},
        include={"quizzes": True}
    )
    if not lesson:
        raise HTTPException(status_code=404, detail="Lesson not found")
        
    # Security check: if it's custom, only the creator can access
    if lesson.is_custom and lesson.user_id != current_user.id:
        raise HTTPException(status_code=403, detail="Not authorized to access this custom lesson")
        
    return {
        "id": lesson.id,
        "title": lesson.title,
        "content": lesson.content,
        "suggested_duration": lesson.duration,
        "quiz": [
            {
                "question": q.question,
                "options": json.loads(q.options) if isinstance(q.options, str) else q.options,
                "correct_answer": q.correct_answer
            } for q in lesson.quizzes
        ]
    }
